version: '3.8'

services:
  api:
    container_name: survival-nexus-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=survival_nexus
      - JWT_SECRET=your-super-secret-key
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - survival-network

  postgres:
    container_name: survival-nexus-db
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=survival_nexus
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - survival-network

volumes:
  postgres_data:

networks:
  survival-network:
    driver: bridge
